config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tasks#index'

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :task, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task: params[:task][:task])
    if @task.save
      redirect_to action: "index"
    else
      render :new
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Lista de Tareas</h1>

<% @tasks.each do |task| %>
<div class="row">
  <div class="col-md">
    <p><%= task.task %></p>
  </div>
  <div class="col-md">
    <p><%= link_to 'Eliminar', task_path(task), method: :delete, data: { confirm: 'Está seguro?' } %></p>
  </div>
</div>
<% end %>

<p><%= link_to "Nueva Tarea", new_task_path %></p>

app/views/tasks/new.html.erb
<% @task.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert">
    <%= message %>
  </div>
<% end %>

<h1>Nueva Tarea</h1>

<%= form_for(@task) do |t| %>
<div class="row">
  <div class="col-md">
    <%= t.text_field :task, placeholder: "Tarea", class:"form-control" %>
  </div>
</div>
<div class="row">
  <div class="col-md">
    <%= t.submit "Crear", class:"btn btn-success" %>
  </div>
</div>
<% end %>